apiVersion: extensions/v1beta1
kind: DaemonSet
metadata: 
  name: appd-infra-agent
spec: 
  template: 
    metadata: 
      labels: 
        name: appd-infra-agent
    spec:
      serviceAccountName: appdynamics-infraviz
      containers:
      - name: appd-infra-agent
        image: appdynamics/machine-agent-analytics:4.5.9
        imagePullPolicy: IfNotPresent
        env:
        - name: APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              key: appd-key
              name: appd-secret
        envFrom:
        - configMapRef:
            name: ma-config
        securityContext:
          privileged: true
        resources:
          limits:
            cpu: "0.6"
            memory: "2Gi"
          requests:
            cpu: "0.3"
            memory: "1G"
        ports:
          - containerPort: 9090
        volumeMounts:
        - name: ma-log-volume
          mountPath: /opt/appdynamics/conf/logging/log4j.xml
          subPath: log4j.xml
        - mountPath: /hostroot/sys
          name: hostroot-sys
          readOnly: true
        - mountPath: /hostroot/proc
          name: hostroot-proc
          readOnly: true
        - mountPath: /hostroot/etc
          name: hostroot-etc
          readOnly: true
        - mountPath: /var/run/docker.sock
          name: docker-sock
      restartPolicy: Always
      volumes:
      - name: ma-log-volume
        configMap:
          name: ma-log-config
      - name: hostroot-proc
        hostPath:
          path: /proc
          type: Directory
      - name: hostroot-sys
        hostPath:
          path: /sys
          type: Directory
      - name: hostroot-etc
        hostPath:
          path: /etc
          type: Directory
      - name: docker-sock
        hostPath:
          path: /var/run/docker.sock
          type: Socket

---
apiVersion: v1
kind: Service
metadata:
  name: appd-infra-agent-service
spec:
  selector:
    name: appd-infra-agent
  ports:
  - name: "9090"
    port: 9090
    targetPort: 9090
status:
  loadBalancer: {}
