apiVersion: v1
data:
  log4j.xml: "<?xml version=\"1.0\" encoding=\"UTF-8\" ?>\n<!DOCTYPE log4j:configuration
    SYSTEM \"log4j.dtd\">\n<log4j:configuration xmlns:log4j=\"http://jakarta.apache.org/log4j/\">\n\n
    \   <appender name=\"ConsoleAppender\" class=\"org.apache.log4j.ConsoleAppender\">\n
    \       <layout class=\"org.apache.log4j.PatternLayout\">\n            <param
    name=\"ConversionPattern\" value=\"%d{DATE} %5p [%t] %c{1}:%L - %m%n\"/>\n        </layout>\n
    \   </appender>\n\n    <appender name=\"FileAppender\" class=\"com.singularity.ee.agent.dbagent.DBAgentLogAppender\">\n
    \       <param name=\"File\" value=\"logs/agent.log\"/>\n        <param name=\"MaxFileSize\"
    value=\"5000KB\"/>\n        <param name=\"MaxBackupIndex\" value=\"5\"/>\n        <layout
    class=\"org.apache.log4j.PatternLayout\">\n            <param name=\"ConversionPattern\"
    value=\"[%t] %d{DATE} %5p %c{1} - %m%n\"/>\n        </layout>\n    </appender>\n\n
    \   <appender name=\"InternalMetricsAppender\" class=\"com.singularity.ee.agent.dbagent.DBAgentLogAppender\">\n
    \       <param name=\"File\" value=\"logs/internal_metrics/internal_metrics.log\"/>\n
    \       <param name=\"MaxFileSize\" value=\"5000KB\"/>\n        <param name=\"MaxBackupIndex\"
    value=\"5\"/>\n        <layout class=\"org.apache.log4j.PatternLayout\">\n        </layout>\n
    \   </appender>\n\n    <logger name=\"com.singularity\">\n        <level value=\"debug\"/>\n
    \   </logger>\n\n    <logger name=\"com.appdynamics\">\n        <level value=\"debug\"/>\n
    \   </logger>\n\n    <!-- Increase these levels for debugging MSSQL Basic Harware
    Metrics code. Setting the loggers' level to\n    debug is usually sufficient-->\n
    \   <logger name=\"com.singularity.ee.agent.dbagent.collector.db.relational.mssql.MSSql2008CollectorDelegate\">\n
    \       <level value=\"debug\"/>\n    </logger>\n\n    <!-- Increase these levels
    for debugging transient channel related code. Setting the first 2 loggers' level
    to\n    debug is usually sufficient-->\n    <!--start-->\n    <logger name=\"com.singularity.ee.agent.dbagent.handler.delegate.relational.ADBTransientOpDelegate\">\n
    \       <level value=\"debug\"/>\n    </logger>\n    \n    <logger name=\"com.singularity.ee.agent.dbagent.handler.executor.ADBTransientOpExecutor\">\n
    \       <level value=\"debug\"/>\n    </logger>\n\n    <logger name=\"com.singularity.ee.agent.dbagent.collector.server.connection.wmi.NativeClient\">\n
    \       <level value=\"debug\"/>\n    </logger>\n    <!--end-->\n \n    <!-- This
    will block httpclient from dumping 'wire' data so passwords et al. won't get into
    the log -->\n    <logger name=\"org.apache.http.wire\">\n        <level value=\"fatal\"/>\n
    \   </logger>\n\n    <root>\n        <priority value=\"error\"/>\n        <appender-ref
    ref=\"ConsoleAppender\"/>\n        <appender-ref ref=\"FileAppender\"/>\n    </root>\n\n</log4j:configuration>\n"
kind: ConfigMap
metadata:
  name: db-log-config